sudo: false
language: ruby
rvm:
  - 2.3.1
  - 2.2.5
  - ruby-head
before_install: gem install bundler -v 1.13.6
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.0
  allow_failures:
    - rvm: ruby-head
